-include ../../../../../petscdir.mk
#requirespackage 'PETSC_HAVE_MONOLIS'

CXXFLAGS  =
SOURCECXX = monolis.cxx
SOURCEF   =
SOURCEH   =
LIBBASE   = libpetscksp
DIRS      =
MANSEC    = KSP
LOCDIR    = src/ksp/ksp/impls/monolis/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
